const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express(),PUB=path.join(__dirname,'public');
app.use(express.json());
app.use(express.static(PUB));
let db={users:[],ingredients:[],recipes:[],recipeIngredients:[]};
const DBF=path.join(__dirname,'db.json');
if(fs.existsSync(DBF)){try{db=JSON.parse(fs.readFileSync(DBF,'utf8'));}catch(e){}}
const save=()=>fs.writeFileSync(DBF,JSON.stringify(db));
const hash=p=>crypto.createHash('sha256').update(p+'fca2024').digest('hex');
const uid=()=>crypto.randomUUID();
const toks={};
const auth=(q,s,n)=>{const t=q.headers.authorization?.replace('Bearer ',''),id=toks[t];if(!id)return s.status(401).json({error:'Unauthorized'});q.uid=id;q.user=db.users.find(u=>u.id===id);n();};
app.post('/api/signup',(q,s)=>{const{name,email,password,restaurantName}=q.body;if(!name||!email||!password||!restaurantName)return s.status(400).json({error:'All fields required'});if(password.length<10)return s.status(400).json({error:'Password must be at least 10 characters'});if(db.users.find(u=>u.email===email))return s.status(400).json({error:'Email already exists'});const u={id:uid(),name,email,password:hash(password),restaurantName};db.users.push(u);save();s.json({ok:true});});
app.post('/api/login',(q,s)=>{const{email,password}=q.body;const u=db.users.find(u=>u.email===email&&u.password===hash(password));if(!u)return s.status(401).json({error:'Invalid email or password'});const t=crypto.randomBytes(32).toString('hex');toks[t]=u.id;s.json({token:t,name:u.name,restaurantName:u.restaurantName});});
app.post('/api/logout',auth,(q,s)=>{delete toks[q.headers.authorization?.replace('Bearer ','')];s.json({ok:true});});
const CONV={'lbs':{to:'oz',f:16},'gal':{to:'fl oz',f:128},'dozen':{to:'each',f:12}};
const calcIng=(d)=>{const c=CONV[d.purchaseUnit],bu=c?c.to:d.purchaseUnit,tot=c?d.purchaseQty*c.f:d.purchaseQty,wf=(+d.wasteFactor||0)/100,cpu=(d.purchaseCost/tot)/(1-wf||1);return{baseUnit:bu,usableCostPerUnit:cpu};};
app.get('/api/ingredients',auth,(q,s)=>s.json(db.ingredients.filter(i=>i.userId===q.uid)));
app.post('/api/ingredients',auth,(q,s)=>{const{name,purchaseUnit,purchaseQty,purchaseCost,wasteFactor}=q.body;if(!name||!purchaseUnit||!purchaseQty||!purchaseCost)return s.status(400).json({error:'Required fields missing'});const{baseUnit,usableCostPerUnit}=calcIng({purchaseUnit,purchaseQty,purchaseCost,wasteFactor});const i={id:uid(),userId:q.uid,name,purchaseUnit,purchaseQty:+purchaseQty,purchaseCost:+purchaseCost,wasteFactor:+wasteFactor||0,baseUnit,usableCostPerUnit};db.ingredients.push(i);save();s.json({ok:true});});
app.put('/api/ingredients/:id',auth,(q,s)=>{const x=db.ingredients.findIndex(i=>i.id===q.params.id&&i.userId===q.uid);if(x<0)return s.status(404).json({error:'Not found'});const{name,purchaseUnit,purchaseQty,purchaseCost,wasteFactor}=q.body;const{baseUnit,usableCostPerUnit}=calcIng({purchaseUnit,purchaseQty,purchaseCost,wasteFactor});db.ingredients[x]={...db.ingredients[x],name,purchaseUnit,purchaseQty:+purchaseQty,purchaseCost:+purchaseCost,wasteFactor:+wasteFactor||0,baseUnit,usableCostPerUnit};save();s.json({ok:true});});
app.delete('/api/ingredients/:id',auth,(q,s)=>{db.ingredients=db.ingredients.filter(i=>!(i.id===q.params.id&&i.userId===q.uid));save();s.json({ok:true});});
const rCost=(r)=>{const ris=db.recipeIngredients.filter(ri=>ri.recipeId===r.id);const tc=ris.reduce((s,ri)=>{const i=db.ingredients.find(i=>i.id===ri.ingredientId);return s+(i?i.usableCostPerUnit*ri.qty:0);},0);return{...r,totalCost:tc,foodCostPct:r.sellingPrice>0?(tc/r.sellingPrice)*100:0,profitMargin:r.sellingPrice>0?((r.sellingPrice-tc)/r.sellingPrice)*100:0};};
app.get('/api/recipes',auth,(q,s)=>s.json(db.recipes.filter(r=>r.userId===q.uid).map(rCost)));
app.post('/api/recipes',auth,(q,s)=>{const{name,sellingPrice,prepNotes,ingredients}=q.body;if(!name)return s.status(400).json({error:'Name required'});const r={id:uid(),userId:q.uid,name,sellingPrice:+sellingPrice||0,prepNotes:prepNotes||'',createdAt:new Date().toISOString()};db.recipes.push(r);if(ingredients){db.recipeIngredients=db.recipeIngredients.filter(ri=>ri.recipeId!==r.id);ingredients.forEach(ing=>db.recipeIngredients.push({id:uid(),recipeId:r.id,ingredientId:ing.ingredientId,qty:+ing.qty}));}save();s.json({ok:true});});
app.put('/api/recipes/:id',auth,(q,s)=>{const x=db.recipes.findIndex(r=>r.id===q.params.id&&r.userId===q.uid);if(x<0)return s.status(404).json({error:'Not found'});const{name,sellingPrice,prepNotes,ingredients}=q.body;db.recipes[x]={...db.recipes[x],name,sellingPrice:+sellingPrice||0,prepNotes:prepNotes||''};if(ingredients){db.recipeIngredients=db.recipeIngredients.filter(ri=>ri.recipeId!==q.params.id);ingredients.forEach(ing=>db.recipeIngredients.push({id:uid(),recipeId:q.params.id,ingredientId:ing.ingredientId,qty:+ing.qty}));}save();s.json({ok:true});});
app.delete('/api/recipes/:id',auth,(q,s)=>{db.recipes=db.recipes.filter(r=>!(r.id===q.params.id&&r.userId===q.uid));db.recipeIngredients=db.recipeIngredients.filter(ri=>ri.recipeId!==q.params.id);save();s.json({ok:true});});
app.get('/api/analytics',auth,(q,s)=>{const rs=db.recipes.filter(r=>r.userId===q.uid).map(rCost);const avg=rs.length?rs.reduce((a,r)=>a+r.totalCost,0)/rs.length:0;const sorted=[...rs].sort((a,b)=>b.profitMargin-a.profitMargin);s.json({totalRecipes:rs.length,avgPlateCost:avg,topRecipes:sorted.slice(0,5),allRecipes:rs});});
app.put('/api/settings',auth,(q,s)=>{const x=db.users.findIndex(u=>u.id===q.uid);if(x<0)return s.status(404).json({error:'Not found'});const{name,restaurantName}=q.body;db.users[x]={...db.users[x],name:name||db.users[x].name,restaurantName:restaurantName||db.users[x].restaurantName};save();s.json({ok:true});});
app.get('*',(q,s)=>s.sendFile(path.join(PUB,'index.html')));
app.listen(3000,()=>console.log('FCA running on 3000'));
