const express=require('express'),path=require('path'),crypto=require('crypto'),Database=require('better-sqlite3');
const app=express(),PUB=path.join(__dirname,'public');
app.use(express.json());
app.use(express.static(PUB));
const DB_PATH=path.join('/app/data','food.db');
const db=new Database(DB_PATH);
db.exec(`
  CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT,email TEXT UNIQUE,password TEXT,restaurantName TEXT);
  CREATE TABLE IF NOT EXISTS ingredients(id TEXT PRIMARY KEY,userId TEXT,name TEXT,purchaseUnit TEXT,purchaseQty REAL,purchaseCost REAL,wasteFactor REAL,baseUnit TEXT,usableCostPerUnit REAL);
  CREATE TABLE IF NOT EXISTS recipes(id TEXT PRIMARY KEY,userId TEXT,name TEXT,sellingPrice REAL,prepNotes TEXT,createdAt TEXT);
  CREATE TABLE IF NOT EXISTS recipeIngredients(id TEXT PRIMARY KEY,recipeId TEXT,ingredientId TEXT,qty REAL);
`);
const hash=p=>crypto.createHash('sha256').update(p+'fca2024').digest('hex');
const uid=()=>crypto.randomUUID();
const toks={};
const auth=(q,s,n)=>{const t=q.headers.authorization?.replace('Bearer ',''),id=toks[t];if(!id)return s.status(401).json({error:'Unauthorized'});q.uid=id;q.user=db.prepare('SELECT * FROM users WHERE id=?').get(id);n();};
app.post('/api/signup',(q,s)=>{const{name,email,password,restaurantName}=q.body;if(!name||!email||!password||!restaurantName)return s.status(400).json({error:'All fields required'});if(password.length<10)return s.status(400).json({error:'Password must be at least 10 characters'});if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return s.status(400).json({error:'Email already exists'});db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(uid(),name,email,hash(password),restaurantName);s.json({ok:true});});
app.post('/api/login',(q,s)=>{const{email,password}=q.body;const u=db.prepare('SELECT * FROM users WHERE email=? AND password=?').get(email,hash(password));if(!u)return s.status(401).json({error:'Invalid email or password'});const t=crypto.randomBytes(32).toString('hex');toks[t]=u.id;s.json({token:t,name:u.name,restaurantName:u.restaurantName});});
app.post('/api/logout',auth,(q,s)=>{delete toks[q.headers.authorization?.replace('Bearer ','')];s.json({ok:true});});
const CONV={'lbs':{to:'oz',f:16},'gal':{to:'fl oz',f:128},'dozen':{to:'each',f:12}};
const calcIng=(d)=>{const c=CONV[d.purchaseUnit],bu=c?c.to:d.purchaseUnit,tot=c?d.purchaseQty*c.f:d.purchaseQty,wf=(+d.wasteFactor||0)/100,cpu=(d.purchaseCost/tot)/(1-wf||1);return{baseUnit:bu,usableCostPerUnit:cpu};};
app.get('/api/ingredients',auth,(q,s)=>s.json(db.prepare('SELECT * FROM ingredients WHERE userId=?').all(q.uid)));
app.post('/api/ingredients',auth,(q,s)=>{const{name,purchaseUnit,purchaseQty,purchaseCost,wasteFactor}=q.body;if(!name||!purchaseUnit||!purchaseQty||!purchaseCost)return s.status(400).json({error:'Required fields missing'});const{baseUnit,usableCostPerUnit}=calcIng({purchaseUnit,purchaseQty,purchaseCost,wasteFactor});db.prepare('INSERT INTO ingredients VALUES(?,?,?,?,?,?,?,?,?)').run(uid(),q.uid,name,purchaseUnit,+purchaseQty,+purchaseCost,+wasteFactor||0,baseUnit,usableCostPerUnit);s.json({ok:true});});
app.put('/api/ingredients/:id',auth,(q,s)=>{const{name,purchaseUnit,purchaseQty,purchaseCost,wasteFactor}=q.body;const{baseUnit,usableCostPerUnit}=calcIng({purchaseUnit,purchaseQty,purchaseCost,wasteFactor});const r=db.prepare('UPDATE ingredients SET name=?,purchaseUnit=?,purchaseQty=?,purchaseCost=?,wasteFactor=?,baseUnit=?,usableCostPerUnit=? WHERE id=? AND userId=?').run(name,purchaseUnit,+purchaseQty,+purchaseCost,+wasteFactor||0,baseUnit,usableCostPerUnit,q.params.id,q.uid);if(!r.changes)return s.status(404).json({error:'Not found'});s.json({ok:true});});
app.delete('/api/ingredients/:id',auth,(q,s)=>{db.prepare('DELETE FROM ingredients WHERE id=? AND userId=?').run(q.params.id,q.uid);s.json({ok:true});});
const rCost=(r)=>{const ris=db.prepare('SELECT * FROM recipeIngredients WHERE recipeId=?').all(r.id);const tc=ris.reduce((s,ri)=>{const i=db.prepare('SELECT * FROM ingredients WHERE id=?').get(ri.ingredientId);return s+(i?i.usableCostPerUnit*ri.qty:0);},0);return{...r,totalCost:tc,foodCostPct:r.sellingPrice>0?(tc/r.sellingPrice)*100:0,profitMargin:r.sellingPrice>0?((r.sellingPrice-tc)/r.sellingPrice)*100:0};};
app.get('/api/recipes',auth,(q,s)=>s.json(db.prepare('SELECT * FROM recipes WHERE userId=?').all(q.uid).map(rCost)));
app.post('/api/recipes',auth,(q,s)=>{const{name,sellingPrice,prepNotes,ingredients}=q.body;if(!name)return s.status(400).json({error:'Name required'});const rid=uid();db.prepare('INSERT INTO recipes VALUES(?,?,?,?,?,?)').run(rid,q.uid,name,+sellingPrice||0,prepNotes||'',new Date().toISOString());if(ingredients){ingredients.forEach(ing=>db.prepare('INSERT INTO recipeIngredients VALUES(?,?,?,?)').run(uid(),rid,ing.ingredientId,+ing.qty));}s.json({ok:true});});
app.put('/api/recipes/:id',auth,(q,s)=>{const{name,sellingPrice,prepNotes,ingredients}=q.body;const r=db.prepare('UPDATE recipes SET name=?,sellingPrice=?,prepNotes=? WHERE id=? AND userId=?').run(name,+sellingPrice||0,prepNotes||'',q.params.id,q.uid);if(!r.changes)return s.status(404).json({error:'Not found'});if(ingredients){db.prepare('DELETE FROM recipeIngredients WHERE recipeId=?').run(q.params.id);ingredients.forEach(ing=>db.prepare('INSERT INTO recipeIngredients VALUES(?,?,?,?)').run(uid(),q.params.id,ing.ingredientId,+ing.qty));}s.json({ok:true});});
app.delete('/api/recipes/:id',auth,(q,s)=>{db.prepare('DELETE FROM recipes WHERE id=? AND userId=?').run(q.params.id,q.uid);db.prepare('DELETE FROM recipeIngredients WHERE recipeId=?').run(q.params.id);s.json({ok:true});});
app.get('/api/analytics',auth,(q,s)=>{const rs=db.prepare('SELECT * FROM recipes WHERE userId=?').all(q.uid).map(rCost);const avg=rs.length?rs.reduce((a,r)=>a+r.totalCost,0)/rs.length:0;const sorted=[...rs].sort((a,b)=>b.profitMargin-a.profitMargin);s.json({totalRecipes:rs.length,avgPlateCost:avg,topRecipes:sorted.slice(0,5),allRecipes:rs});});
app.put('/api/settings',auth,(q,s)=>{const{name,restaurantName}=q.body;db.prepare('UPDATE users SET name=?,restaurantName=? WHERE id=?').run(name||q.user.name,restaurantName||q.user.restaurantName,q.uid);s.json({ok:true});});
app.get('*',(q,s)=>s.sendFile(path.join(PUB,'index.html')));
app.listen(process.env.PORT||3000,()=>console.log('FCA running on '+(process.env.PORT||3000)));
